import type { Movie, Seat } from '../types';

export const MOCK_MOVIES: Movie[] = [
  {
    _id: '1',
    title: 'Avengers: Endgame',
    description: 'The epic conclusion to the Infinity Saga.',
    duration: 181,
    genre: ['action', 'sci-fi'],
    language: 'English',
    releaseDate: '2024-01-15',
    posterUrl: 'https://images.unsplash.com/photo-1534809027769-b00d750a6bac?auto=format&fit=crop&q=80&w=400&h=600',
    rating: 'C13',
    isActive: true,
  },
  {
    _id: '2',
    title: 'Spider-Man: No Way Home',
    description: 'Peter Parker\'s secret identity is revealed to the entire world.',
    duration: 148,
    genre: ['action', 'adventure'],
    language: 'English',
    releaseDate: '2024-02-20',
    posterUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&q=80&w=400&h=600',
    rating: 'P',
    isActive: true,
  },
  {
    _id: '3',
    title: 'Dune: Part Two',
    description: 'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge.',
    duration: 166,
    genre: ['sci-fi', 'drama'],
    language: 'English',
    releaseDate: '2024-03-01',
    posterUrl: 'https://images.unsplash.com/photo-1547823528-9122c60c87b9?auto=format&fit=crop&q=80&w=400&h=600',
    rating: 'C16',
    isActive: true,
  },
  {
    _id: '4',
    title: 'Oppenheimer',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    duration: 180,
    genre: ['biography', 'drama'],
    language: 'English',
    releaseDate: '2023-07-21',
    posterUrl: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?auto=format&fit=crop&q=80&w=400&h=600',
    rating: 'C18',
    isActive: true,
  },
  {
    _id: '5',
    title: 'The Batman',
    description: 'When a sadistic serial killer begins murdering key political figures in Gotham.',
    duration: 176,
    genre: ['action', 'crime'],
    language: 'English',
    releaseDate: '2022-03-04',
    posterUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?auto=format&fit=crop&q=80&w=400&h=600',
    rating: 'C16',
    isActive: true,
  },
  {
    _id: '6',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology.',
    duration: 148,
    genre: ['action', 'sci-fi'],
    language: 'English',
    releaseDate: '2010-07-16',
    posterUrl: 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?auto=format&fit=crop&q=80&w=400&h=600',
    rating: 'C13',
    isActive: true,
  },
  {
    _id: '7',
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    duration: 169,
    genre: ['adventure', 'sci-fi'],
    language: 'English',
    releaseDate: '2014-11-07',
    posterUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ce7a?auto=format&fit=crop&q=80&w=400&h=600',
    rating: 'P',
    isActive: true,
  },
  {
    _id: '8',
    title: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality.',
    duration: 136,
    genre: ['action', 'sci-fi'],
    language: 'English',
    releaseDate: '1999-03-31',
    posterUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=400&h=600',
    rating: 'C16',
    isActive: true,
  }
];

export const MOCK_SEATS: Seat[] = Array.from({ length: 80 }, (_, i) => ({
  _id: String(i),
  row: String.fromCharCode(65 + Math.floor(i / 10)),
  number: (i % 10) + 1,
  type: Math.floor(i / 10) >= 6 ? 'vip' : 'standard',
  status: Math.random() > 0.7 ? 'booked' : Math.random() > 0.9 ? 'locked' : 'available',
}));
